name: build and test feature branch
on: 
  push:
    branches:
      - feature/*  
jobs: 
  build-feature:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: pull and checkout from git repository

      run:
        echo "pulling and checking out from git repository"

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' #see 'supported distributions' for availible options'
        java-version: '17'
   # - run: java HelloWorldApp.java ejemplo ejecuacion
    - name: build with maven
      run: 
        mvnw clean install
        echo "build with maven"
        